name: CI/CD GitHub Actions Only

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: 'dummy_id'
          vercel-project-id: 'dummy_id'
          working-directory: ./tiktok-clone
